
ALTER TABLE public.players 
  ADD COLUMN IF NOT EXISTS rebuy_tendency NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS recovery_rate NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS archetype TEXT DEFAULT NULL;
